# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    serializer:
        default_context:
            json_encode_options: 448

    exceptions:
        DomainException:
            status_code: 400
            log_level: warning

    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
